{
 "title": "System Health & Performance Overview",
 "tags": [
  "overview",
  "system",
  "demo"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,15m,1h" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "$datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "datasource" },
  {
   "title": "Total HTTP Requests Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Overall Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(errors_total[5m])) / sum(rate(http_requests_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Current Active Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(active_users)" }
   ]
  },
  {
   "title": "Top 5 Error Types",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(5, sum by (error_type) (errors_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Application (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (app) (rate(http_requests_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Method(Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_requests_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Endpoint (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}